### ISSUE TITLE
Silent exception in singleton.js

### ISSUE THREAD

**Issue by davidverriere** [seraum/fortressjs#3]
In getCaller function there is a silent exception catch 👍 
err.stack.shift().getFileName();
stack is not an array, so shift() does not exist

![image](https://user-images.githubusercontent.com/6039093/30519035-22ae7c82-9b8d-11e7-963d-ca9739c3aa21.png)

**Comment by adrien-thierry** [comment]
It was a hack to restrict rights over memory, err.stack was an array

but the API of V8 has changed, so I need to change this

It's not a silent exception catch btw

**Comment by adrien-thierry** [comment]
Updated with commit ff72475
